### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by jayvdb** [webpy/webpy.github.com#134] opened 2020-01-10 11:00 UTC
https://webpy.org/ (https) says it has a bad certificate, probably because of mismatch of domain.

**Comment by iredmail** [comment] 2020-01-10 11:04
Have to leave it to @anandology :)

**Comment by anandology** [comment] 2020-01-11 07:10
Looks like an issue with GitHub Pages. Waiting for it to reissue the certificates. The message says, they need 24 hours to do that. It is already 20 hours since the issue is reported. I'll ping github if the issue is not resolved in another 4 hours.

![Screen Shot 2020-01-11 at 12 38 35 PM](https://user-images.githubusercontent.com/7569/72200421-562c9d00-346f-11ea-976a-8d1b30952ece.png)

**Comment by cclauss** [comment] 2020-01-11 07:18
Closing.  The site is back in action.  Thanks for reporting this.

**Closed by cclauss** 2020-01-11 07:18 UTC
